// import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';
// import styles from '@/styles/Home.module.css';

// const inter = Inter({ subsets: ['latin'] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Klasifikasi</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <h1>Halaman Klasifikasi</h1>
//       </main>
//     </>
//   );
// }

// pages/index.js
import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import FormComponent from '../../components/FormComponent';

const HomePage = () => {
  return (
    <div className="container mt-5">
      <h1>Next.js Form with Bootstrap</h1>
      <FormComponent />
    </div>
  );
};

export default HomePage;
